export MODERATION_BOT_DATABASE_HOST=""
export MODERATION_BOT_DATABASE_NAME=""
export MODERATION_BOT_DATABASE_USERNAME=""
export MODERATION_BOT_DATABASE_PASSWORD=""
export MODERATION_BOT_DISCORD_AUTH_TOKEN=""

dotnet run --config Release --project ModerationBot
